---
{{- $crdReplicatorConfig := (merge (dict "name" "crd-replicator" "module" "dispatcher") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $crdReplicatorConfig | nindent 6 }}
  template:
    metadata: 
    {{- if .Values.crdReplicator.pod.annotations }}
      annotations:
        {{- toYaml .Values.crdReplicator.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $crdReplicatorConfig | nindent 8 }}
        {{- if .Values.crdReplicator.pod.labels }}
           {{- toYaml .Values.crdReplicator.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
      containers:
        - image: {{ .Values.crdReplicator.imageName }}{{ include "liqo.suffix" $crdReplicatorConfig }}:{{ include "liqo.version" $crdReplicatorConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ $crdReplicatorConfig.name }}
          command: ["/usr/bin/crd-replicator"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.useNewAuth }}
          args:
          - "--useNewAuth"
          {{- end }}
          resources:
            limits:
              cpu: 30m
              memory: 50M
            requests:
              cpu: 30m
              memory: 50M
---