name: Release Pipeline
on:
  release:
    types:
      - published

jobs:

  krew:
    runs-on: ubuntu-latest
    steps:

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.43
